// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gen_prm_keys
List gen_prm_keys(int prm_comb_num, std::string pkey_date, IntegerVector p_index, int digit_num);
RcppExport SEXP _phaseX_gen_prm_keys(SEXP prm_comb_numSEXP, SEXP pkey_dateSEXP, SEXP p_indexSEXP, SEXP digit_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type prm_comb_num(prm_comb_numSEXP);
    Rcpp::traits::input_parameter< std::string >::type pkey_date(pkey_dateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p_index(p_indexSEXP);
    Rcpp::traits::input_parameter< int >::type digit_num(digit_numSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_prm_keys(prm_comb_num, pkey_date, p_index, digit_num));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phaseX_gen_prm_keys", (DL_FUNC) &_phaseX_gen_prm_keys, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_phaseX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
