# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gen_prm_keys <- function(prm_comb_num, pkey_date, p_index, digit_num) {
    .Call('_phaseX_gen_prm_keys', PACKAGE = 'phaseX', prm_comb_num, pkey_date, p_index, digit_num)
}

